name: Run Selenium tests with behave and Allure reporting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install selenium behave allure-behave
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests with behave and Allure reporting
      run: |
        source ./env/bin/activate
        timestamp=$(date +%Y_%m_%d_%H_%M_%_S)
        report_directory="allure_reports/run_${timestamp}"
        mkdir -p "$report_directory"
        behave -f allure_behave.formatter:AllureFormatter -o "$report_directory" -f pretty
